# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

# define the VM image I want to use for my build
pool:
  vmImage: "Ubuntu 20.04"

# define variables to use during the build
variables:
  projectFile: "Server/Api/Api.csproj"
  idPServerFile: "Server/IdentityServer/IdentityServer.csproj"
  buildConfiguration: "Release"
  projectFolder: "TheFortress.Client"
  buildOutputFolder: "TheFortress.Client/dist/html"

# define the steps of the build
steps:
  ## Run the npm install/build
  - script: |
      pushd $(projectFolder) && npm install && popd
      pushd $(projectFolder) && npm run build && popd
  ## Copy the client to the staging directory
  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(buildOutputFolder)"
      contents: "**/*"
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      cleanTargetFolder: true

  ## Archive the files into a zip file for publishing
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/bundle_ng.zip"
      includeRootFolder: false

  ## Publish the zip file
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/bundle_ng.zip"

  ## Run the dotnet build/publish
  - script: |
      dotnet build $(projectFile) --configuration $(buildConfiguration)
      dotnet publish $(projectFile) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)_build
  ## Archive the files into a zip file for publishing
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)_build
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/bundle_api.zip"
      includeRootFolder: false

  ## Publish the zip file
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/bundle_api.zip"

  ## Build the id server
  - script: |
      dotnet build $(idPServerFile) --configuration $(buildConfiguration)
      dotnet publish $(idPServerFile) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)_build
  ## Archive the files into a zip file for publishing
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)_build
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/bundle_idp.zip"
      includeRootFolder: false

  ## Publish the zip file
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/bundle_idp.zip"
